name: Deploy Project

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Deploy to production via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            .git/**
            .github/**
            node_modules/**
            .env
            *.log
            .idea/**
            .vscode/**
            .ftp-deploy-sync-state.json
            private_uploads/**          # если не хотите загружать загрузки
            logs/**
            sessions/**
            data/**
