name: Deploy Project

on:
  push:
    branches: [ main, master ] # Укажите вашу основную ветку
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy to production
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          # Опционально: исключить ненужные папки и файлы
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .env